version: "3.9"

services:
  mongo:
    image: mongo:${MONGO_TAG:-3.6.23-xenial}
    restart: always
    ports:
      - ${MONGO_PORT:-27017}:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USER:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASS:-secret}

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT:-8081}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USER:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASS:-secret}
